# =============================================================
#  Reverse proxy - ÉTAT DE DÉPART (NON sécurisé)
#  À durcir : TLS (Faille 2), en-têtes + rate-limiting (Faille 3)
# =============================================================
server {
    listen 80;
    server_name localhost;

    # (!) pas de TLS, pas de redirection HTTPS
    # (!) server_tokens actif : la version de Nginx est divulguée
    # (!) aucun en-tête de sécurité, aucune limitation de débit

    location / {
        proxy_pass http://web:80;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }
}
