server {
    listen 80;
    server_name localhost;

    location / {
        # On redirige le trafic vers le conteneur 'xvwa' sur le port 80 (Apache)
        proxy_pass http://xvwa:80;
        
        # On transmet les informations d'origine pour que PHP sache d'où vient la requête
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto $scheme;
    }
}